### ISSUE TITLE
undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by s-j-99** [MischaSchwendy/EVICAN-MRCNN#3]
Hi, 

I keep getting this error when I try to run training as suggested:

```
python3 evican.py train --dataset=~/EVICAN –model=../../model_weights/mask_rcnn_balloon.h5
Traceback (most recent call last):
  File "/home/ubuntu/Mask_RCNN/samples/coco/evican.py", line 47, in <module>
    from pycocotools.coco import COCO
  File "/home/ubuntu/Mask_RCNN/samples/coco/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/ubuntu/Mask_RCNN/samples/coco/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: /home/ubuntu/Mask_RCNN/samples/coco/pycocotools/_mask.so: undefined symbol: _Py_ZeroStruct
```

I believe this is because of some inconsistencies between Python versions. Could you please share what is the Python version you used to develop evican.py?

I followed all the instructions otherwise, including installing Mask R-CNN from Matterport's GitHub, naming the data files correctly and moving evican.py and pycocotools to Mask_RCNN/samples/coco

**Comment by s-j-99** [comment]
I solved the issue by downloading `pycocotools` from github and running `make` under PythonAPI
